baseURL = "https://www.deako.dev/"
languageCode = "en-us"
title = "deako"

[params]
  author = "Zachary Deak"
  description = "DO. PhD student in Human-Centered Computing at Georgia Tech."

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "monochrome"
  noClasses = true
